// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_SJOUjGjWOd17n2ltuIJScu96veGw-kc',
    appId: '1:1005135440777:web:2610a8ca24a5319846cf58',
    messagingSenderId: '1005135440777',
    projectId: 'medico-e5fee',
    authDomain: 'medico-e5fee.firebaseapp.com',
    storageBucket: 'medico-e5fee.firebasestorage.app',
    measurementId: 'G-51E7YP2NN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzAP8vX2rYruK4iL8e-30EV2BVj0nhv4',
    appId: '1:1005135440777:android:8b934433a79ed05746cf58',
    messagingSenderId: '1005135440777',
    projectId: 'medico-e5fee',
    storageBucket: 'medico-e5fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBs_WvSc2CbNfG9VAL8nH2wHUWIFHhHM',
    appId: '1:1005135440777:ios:1408e3c0ced7be3046cf58',
    messagingSenderId: '1005135440777',
    projectId: 'medico-e5fee',
    storageBucket: 'medico-e5fee.firebasestorage.app',
    iosBundleId: 'com.example.medico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBs_WvSc2CbNfG9VAL8nH2wHUWIFHhHM',
    appId: '1:1005135440777:ios:1408e3c0ced7be3046cf58',
    messagingSenderId: '1005135440777',
    projectId: 'medico-e5fee',
    storageBucket: 'medico-e5fee.firebasestorage.app',
    iosBundleId: 'com.example.medico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_SJOUjGjWOd17n2ltuIJScu96veGw-kc',
    appId: '1:1005135440777:web:9afd1ed878c8262346cf58',
    messagingSenderId: '1005135440777',
    projectId: 'medico-e5fee',
    authDomain: 'medico-e5fee.firebaseapp.com',
    storageBucket: 'medico-e5fee.firebasestorage.app',
    measurementId: 'G-1R3KEF0ET2',
  );
}
